market:
  geography: US
  eligible_patients: 1200000      # neb-eligible COPD (proxy)
  
bass:
  p: 0.03                         # innovation coefficient
  q: 0.40                         # imitation coefficient
  
gbdt_overlay:
  use: true
  features: [price_index, access_tier_idx, specialist_density_proxy, marketing_proxy]
  n_estimators: 100
  max_depth: 3
  
price_access:
  list_price_month_usd: 2950
  gtn_pct: 0.65                   # net = list * gtn_pct
  access_tier: PA                 # OPEN | PA | NICHE
  
economics:
  wacc_annual: 0.10
  cogs_pct: 0.15
  sga_launch_annual: 350000000
  sga_decay_to_pct: 0.5
  horizon_years: 10
  
simulation:
  periods_quarterly: 40           # 10 years * 4 quarters
  monte_carlo_runs: 10000
  p_sd: 0.01                      # standard deviation for p
  q_sd: 0.05                      # standard deviation for q
  gtn_sd: 0.05                    # standard deviation for gross-to-net
  price_sd: 0.10                  # standard deviation for price
  
random_seed: 42                   # for reproducibility
